### ISSUE TITLE
[RESOLVED] Compiler error in Unity build

### ISSUE THREAD

**Issue by Keepps** [VeriorPies/ParrelSync#102]
**Describe the bug**
Compiler error when building project in Unity if referring to ParrelSync.ClonesManager.  Compiles fine in the Editor.

**To Reproduce**

Put this in code and build the project in Unity:

            if (ParrelSync.ClonesManager.IsClone())
            {
                Debug.LogWarning("Foo");

            }

**Expected behavior**
Should compile when building.

**Enviroment (please complete the following information):**
 - Unity Editor 2020.3.44f1 Personal
 - ParrelSync Version: 1.51
 - OS Version: Windows 11 Home 10.0.22621 Build 22621

BTW this is other amazing, huge timesaver.  Thanks!

**Comment by 314pies** [comment]
Hi Keepps,
It looks like you are missing `#if UNITY_EDITOR` flag to exclude ParrelSync from your build (ParrelSync should be editor only)

Example code snippet:
https://github.com/VeriorPies/ParrelSync/wiki/List-of-APIs#clonesmanagerisclone

**Comment by Keepps** [comment]
Aha! Many thanks.
