### ISSUE TITLE
Additional symbolic links

### ISSUE THREAD

**Issue by albpb2** [VeriorPies/ParrelSync#107]
I wonder if there's a way to extend the symbolic links ParrelSync creates (Packages, etc.) in case there are other folders we'd like to clone by default.

Thanks for this amazing tool :)

**Comment by TheXRMonk** [comment]
The 1.5.2 release comes with this feature.

But you can also just do this manually. I recommend [link shell extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html)

**Comment by albpb2** [comment]
Thank you! I was doing it manually, just wondered if there was a way in ParrelSync. Glad to know it's coming in 1.5.2 :)
