### ISSUE TITLE
Remove "Star on Github" prompt

### ISSUE THREAD

**Issue by Agoxandr** [VeriorPies/ParrelSync#108]
I have automation scripts that involve opening the Editor that stop indefinitely when this prompt shows up, because they require user action.
While I in theory have nothing against such a prompt, a different solution would be very much appreciated. Otherwise I will have to manually remove the package on every import in powershell script or come up with a different convoluted solution.

**Comment by Agoxandr** [comment]
A file or setting that would turn it off for every machine would work too.

**Comment by 314pies** [comment]
Hi Agixabdr,  
The prompt can be removed by deleting[this file](https://github.com/VeriorPies/ParrelSync/blob/master/ParrelSync/Editor/NonCore/AskFeedbackDialog.cs) :)

**Comment by Agoxandr** [comment]
Thanks a lot. Simply writing this Editor player pref on editor start would resolve this.
