### ISSUE TITLE
[Feature Request] ParrelSync for MacOS

### ISSUE THREAD

**Issue by Avalin** [VeriorPies/ParrelSync#109]
**Describe the feature you'd like**
"Please create a feature request if you want Mac/Linux support to be added." the official Unity thread said. I didn't find one in here, so I'd like to add one. Would love to be able to test my multiplayer games more efficiently from MacOS. Using ParrelSync would be lovely. :)

**Comment by julionav** [comment]
This already works on MacOS. At least it does on my M1 pro
