### ISSUE TITLE
[BUG] 1.5.2 breaks compatibility with .NET 2.0 Standard

### ISSUE THREAD

**Issue by ktyldev** [VeriorPies/ParrelSync#110]
**Describe the bug**

Version 1.5.2 breaks compatibility with .NET 2.0 Standard projects due to the inclusion of a C# 8.0 feature. This should be at least a MINOR version upgrade as per [semver](https://semver.org/).

**To Reproduce**
1. Create a Unity project using 2020.3.38f1
2. Import ParrelSync 1.5.1
3. Confirm no compilation errors
4. Remove 1.5.1, import 1.5.2
5. Compilation error on [Editor/Preferences.cs:91](https://github.com/VeriorPies/ParrelSync/blob/master/ParrelSync/Editor/Preferences.cs#L91C36-L91C36) due to the use of a [nullable reference type](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-80).

**Expected behavior**

No compilation errors.

**Screenshots/Video**
If applicable, add screenshots or video link( Youtube/Vimeo) to help explain the problem.

![image](https://github.com/VeriorPies/ParrelSync/assets/7398424/bb6bb1d1-dd2c-45f4-8332-f2a35554b68b)

**Enviroment (please complete the following information):**
 - Unity Editor Version: 2020.3.38f1
 - ParrelSync Version: 1.5.2
 - OS Version: Windows 11 22H2

**Additional context**

**Comment by 314pies** [comment]
duplicate #116
