### ISSUE TITLE
[BUG] Clone Unity UI is completly pink

### ISSUE THREAD

**Issue by iTim69** [VeriorPies/ParrelSync#113]
**Describe the bug**
After opening the clone, the whole Unity UI is pink (see image). Cloning worked without throwing any errors.

**To Reproduce**
I tried to reproduce the bug but i cant. Parrel Sync was working in the project initially but broke while i was developing. I thought it was because of a package i installed so i tried all of them in a empty project but that didnt cause the error. I cannot point the exact reason for it. I am hoping the problem (and a fix or cause) is known. But the project was moved to another PC using an external drive  (zipped), maybe that could cause the issue?

**Expected behavior**
A normal colored UI of Unity should open.

**Screenshots/Video**
![ParrelSyn](https://github.com/VeriorPies/ParrelSync/assets/98386392/c0d1c349-5a49-419a-8356-1fdac3222099)

**Enviroment (please complete the following information):**
 - Unity Editor Version: (For Example: Windows 2021.3.28f1)
 - ParrelSync Version: 1.5.2
 - OS Version: Windows 10

**Additional context**
I am developing an app for Android (pico4 / Quest) using URP.

**Comment by 314pies** [comment]
This doesn't seem like a ParrelSync issue but more like a driver/graphics API issue.  
(Resolving issue, feel free to re-open it if you believe this is related to ParrelSync)
