### ISSUE TITLE
[Feature Request] Support for Linux

### ISSUE THREAD

**Issue by wcampospro** [VeriorPies/ParrelSync#12]
**Describe the feature you'd like**
Hi, the Linux community and many more I'm sure would really appreciate Linux support for this project.
Especially since dedicated servers and supporting multiple platforms are very valuable things to have as a game.

**Describe alternatives you've considered**
The alternative is to create a Bash, Python, DotNetCore script that does this.
if it was a DotNetCore script, it will be very simple to integrate into Unity.

**Additional context**
![image](https://user-images.githubusercontent.com/16523949/97323651-3fa0d800-182e-11eb-81ad-94da6fe87668.png)

![image](https://user-images.githubusercontent.com/16523949/97323703-50514e00-182e-11eb-9ce3-d80a7fe2b39d.png)

Thank you!

**Comment by 314pies** [comment]
Thanks for reaching out!
Will try my best to add it at my spare time ;)

(If someone also need Linux support see this thread, please leave a reaction or comment so we know you need it!)

**Comment by IamCrypt0n** [comment]
ParrelSync is such a great tool. Many of my colleagues and me wish to be able to use it on our linux machines.
Thank you for you work @314pies

**Comment by wcampospro** [comment]
Already created a pull request solving this "Issue".
Full support for Linux, tested on [5.8.18-1-MANJARO].

**Comment by 314pies** [comment]
The new release with Linux support
https://github.com/VeriorPies/ParrelSync/releases/tag/1.4.2
