### ISSUE TITLE
[Feature Request] Longer file path names >255 chars

### ISSUE THREAD

**Issue by clearskystudio** [VeriorPies/ParrelSync#13]
I'm currently having issues with my project because of >255 path strings which the clone generator isn't able to parse throwing a file not found error message.
I'm not sure whether it's a serious restriction in the script or not, so I decided to post it as a Feature Request. 
Such a feature would be greatly appreciated. Thanks!

**Comment by 314pies** [comment]
This is actually the [default path length limit of windows 10](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation). 
As far as I know, Unity editor also has a 255 characters limitation with project path. There's probably not much we can do here.

**Comment by clearskystudio** [comment]
Fair enough. It's still possible to maintain all your needs within 260 chars range by optimizing the path names. Which I did 😄
