### ISSUE TITLE
[Feature Request]  Customizable CloneNameSuffix for an easier alt-tab search

### ISSUE THREAD

**Issue by mccorkle** [VeriorPies/ParrelSync#14]
**Describe the feature you'd like**
It would be awesome to be able to set the name of the clones, or to have the "arguments" asked for ahead of creating the clone folder and included it in clone folder name instead of `clone_`.

The benefit would be that the window title (and alt-tab and window-tab preview titles) will show the folder name at the beginning of the window name and it would make it easier for me to find my "server", "host", "client", etc clones.
![clone names so I can find my named clones](https://user-images.githubusercontent.com/2091058/97938372-43ad8800-1d4f-11eb-900f-7cb908ac2357.png)

If you were to go with the option of allowing me to set `CloneNameSuffix` before I create the clone, could you also please expose an API such as `ClonesManager.GetCloneName()` so that I can use that clone name so that I can skip the need for the arguments -- so that when I create a clone with 'server' in its folder name, I likely want to use that to enable some server behaviors.  

**Describe alternatives you've considered**
My current alternative is to mentally keep record of which clone is meant to run server, client, host (e.g. Clone_0 is host, clone_1 is server, main is client, etc) 

I may just be missing a better way to find my various clones when alt-tabbing.  Please educate me if that is the case.

**Comment by 314pies** [comment]
It should be more convenience if we can manually name the project folder.  
But before adding a new feature(more code = more potential bugs lol), maybe you can try to use "win" + "→" keys to keep the clone editor at the right side of the screen, so when we are in the original editor and wanna do the test, just press "win" + "←" keys and the clone editor will show up.  After testing, just select the editor on the left (original editor) and press "win" + "↑" keys and we can get back to work.  

![hotkey](https://user-images.githubusercontent.com/20402192/97983086-b1b98400-1e0f-11eb-993d-3e5b6c5e6b79.gif)

Let me know if this tip is convenience enough for you :)

**Comment by mccorkle** [comment]
Oh yeah, I've got a work around that just requires the extra mental load of remembering which clone is which role and just alt-tabbing to it.  I'm just thinking I'll more than likely will have forgotten those associations if I have to work on another project and come back to this one in 3 months -- hence the request for the window title having the specifics in it so that I can just "know by looking at it".  

I'm still very jr in unity editor hacking, but I'll take a stab at making the clone_X name optionally settable for my local project and send you a PR to see if it works for you.  I'll even take a look at the `ClonesManager` and see if I can add that call for clone folder name too, but no promises there.

**Comment by 314pies** [comment]
Sure, a PR with such nice feature is always welcome. 
Let me know if you need any extra help or info. 
(Quite busy recently, but I think I may able to work on this feature next month, which I have relatively more spare time. Of course, a contribution from the community will be greatly appreciated! )

**Comment by pixeldashgames** [comment]
@314pies if you aren't working on it I could take care of that for you, though I'm quite new to GitHub

**Comment by pixeldashgames** [comment]
@pixeldashgames my bad you already did it, hadn't checked the code

**Comment by 314pies** [comment]
Doesn't seems to have many requests on this feature. 
Close it for now.
