### ISSUE TITLE
[BUG] Clones running after unexpected Unity process killed

### ISSUE THREAD

**Issue by betomaluje** [VeriorPies/ParrelSync#17]
**Describe the bug**
The Clone Manager shows my 2 clone projects running (which is not true since I'm trying to find them on my computer's tasks and they are not there) but now I'm unable to open them or delete them. I'm unable to do anything and don't know what to do.

**To Reproduce**
1. Have any clone up and running
2. I run out of battery on my computer when this happened but it also happened when I stopped the main Unity process since it wasn't responding (Ctrl+Alt+Delete or with the PC's Task Manager)
3. After restarting Unity, open the Clone Manager
4. See error. One is unable to press any button for restarting or deleting a clone. But it says they are running

**Expected behavior**
One would expect the clone to be killed as well with the main process so whenever Unity is opened again, one is able to open the clone normally

**Screenshots/Video**
If applicable, add screenshots or video link( Youtube/Vimeo) to help explain the problem.
<img width="443" alt="Screenshot 2020-11-18 at 08 26 02" src="https://user-images.githubusercontent.com/1640449/99498571-fbf64580-2977-11eb-95af-90352a2c7800.png">

**Enviroment (please complete the following information):**
 - Unity Editor Version: macOS Catalina  with Unity 2019.4.11f1
 - ParrelSync Version [e.g. 1.4.1]

**Additional context**
I won't expect ParrelSync to kill itself if the main process is suddenly killed, but it would be nice to be able to kill a clone or restart it if anything happened no? My only solution now is going to the folder, delete the whole folder and create a new clone (which I don't know if it's going to be seen as number 3 in my case or start from scratch)

**Comment by 314pies** [comment]
HI betomaluje,
Currently, ParrelSync determining the clone running status by checking the ```Temp/UnityLockfile```.
If the same thing happen again, as temporary solution, instead of the entire clone project folder, try deleting the ```Temp``` folder. This should reset the clone running status in Clones Manager.  
Will taker a further look to this issue later.  

![image](https://user-images.githubusercontent.com/20402192/99510153-a9417b80-29c1-11eb-86d4-e5c77950606f.png)

**Comment by 314pies** [comment]
This seems to be an aged Unity issue.
In Windows editor, ParrelSync will also check the ```UnityLockfile``` lock status. 
However, Unity won't lock the ```UnityLockfile``` on Mac and Linux so the same technique won't apply.
Have added it to the Troubleshooting & FAQs Wiki page.

Will make an update if found any more reliable way to check the project running state.
