### ISSUE TITLE
[BUG] The preferences are not "easily" syncronized

### ISSUE THREAD

**Issue by guplem** [VeriorPies/ParrelSync#2]
**Describe the bug**
When changing the preferences in the main project, the changes are not reflected in the clones.

**To Reproduce**
I detected this error by doing the following with a clone running: 
1. In the main project > Edit > Preferences > General
2. Disabled "Show Asset Store Search Hits"
The value is not synchronized to the clone even if the clone is restarted.

I was using ParrelSync 1.2. However, I did the following and nothing happened:
1. Deleted the clones.
2. Updated ParrelSync to v 1.3.2
3. Closed and relaunched the main project
4. After checking that the preferences are set as I wanted, create a new clone.
The clone did have the change in preferences that I did in the main project.

**Expected behavior**
The clone should change the preferences straight away imitating the ones in the main project or, at least, a message in the console saying what steps should be done to sync the preferences must be done.

**Enviroment (please complete the following information):**
 - Unity Editor Version: Windows 2019.3.10f1
 - ParrelSync Version: 1.2

**Comment by 314pies** [comment]
As far as I know, Unity preference(Edit -> Preferences) aren't per project base. There are editor preference and aren't related to project itself, so there's no need to sync it over project.
(Close and re-opened the cloned project will load the new editor preference)
