### ISSUE TITLE
[Question] Parallel sync'ed clone editor window doesnt have authority

### ISSUE THREAD

**Issue by nikil07** [VeriorPies/ParrelSync#20]
Not sure if I missed something, but the cloned editor window doesn't have authority ever, and I cannot do any client actions on it.

**Comment by 314pies** [comment]
This seems more related to the Networking framework/library you are using.
Are you using Mirror?

**Comment by nikil07** [comment]
Yes yes Mirror. 

So this has more to do with Mirror than with parallel sync?

**Comment by 314pies** [comment]
Yes, this is a Mirror question.
And btw, you might want to take a look to the Mirror Doc which contains useful information about Network Authority.

https://mirror-networking.com/docs/Articles/Guides/Authority.html

**Comment by nikil07** [comment]
I went over to the discord and asked around. 

They are saying they are not having any issue, and that it works fine for them.

So maybe its something on my side only. Will go through again,.

**Comment by 314pies** [comment]
Hi nikil07,
Is this problem solved?
