### ISSUE TITLE
Unity keeps Resolving packages when switching between clone and original.

### ISSUE THREAD

**Issue by tarsss** [VeriorPies/ParrelSync#23]
I have a single clone of my project to test Mirror multiplayer. But when I switch between original and clone project editors, "Resolving packages" window appears, and takes few seconds to complete, which is kinda annoing. I already tried to clone original project again, but still, the issue is there. It seems like packages between original and clone are conflicting in some way (?). Is there any way to fix this? Thanks.

**Comment by 314pies** [comment]
Hi tarsss,
Thanks for reaching out.
Would you mind to show us how to reproduce it so we can take a deeper look?

**Comment by tarsss** [comment]
Thanks for your quick reply! 
The steps for replicating the issue:

1. Create a new 2D Unity project with Unity Hub
2. Clone it, and open the cloned project via Clone Manager
3. Switch between original and cloned editor windows several times

The Unity version is 2019.4.17f1. Also tried with 2019.4.9f1 though.
Here's link to the archive with original and cloned projects: https://drive.google.com/file/d/1IRObhri95PFqHiC1mj0ZIYrJ55LHHEZp/view?usp=sharing

**Comment by tarsss** [comment]
I've replaced clone's Packages folder with the one from original project. Looks like the problem is solved now

**Comment by anisimovih** [comment]
You can also turn off Auto Refresh in the preference panel and save changes only when you actually change something.

**Comment by TheYellowArchitect** [comment]
> I've replaced clone's Packages folder with the one from original project. Looks like the problem is solved now
Huh. Thank you guys. I was at a loss on what was at fault
https://github.com/VeriorPies/ParrelSync/issues/29

Works now. I just deleted the symlink to Packages, and just copy-pasted the Packages. It just works.

**Comment by 314pies** [comment]
This have been fixed in the [latest released](https://github.com/VeriorPies/ParrelSync/releases/tag/1.4.3).
Please check it out.
