### ISSUE TITLE
Update note for the wiki page or the read me page

### ISSUE THREAD

**Issue by markyj2015** [VeriorPies/ParrelSync#25]
Hi,
I recently tried using the plugin in a project, however after cloning a project, I was unable to actually open a cloned editor. Instead what happened was that the Unity Hub application would load and I was unable to load a cloned editor.
After some Googling, I was unable to find any instances where this had already happened before.
Today after some sleep, I thought to check how I had things setup and I think I found the issue.
I had my project files in a mapped drive (the files were essentially symbolic links). I copied my entire project to its own folder from the root (C:) drive and retried, it then worked with absolutely no issues.
Some things to note in my initial setup.
The files are/were hosted in a Onedrive folder, due to issues with Unity returning paths that were too long I resorted to mapping the folder to a drive on my machine to overcome this.
I also had these files setup to use github so I can learn and start using version control (while I have had github for a number of years, I have only just started to try and actually use it, so I am still learning).
So since I believe that the issue here was using mapped drives and symbolic links, it may be worth noting this on an FAQ or the wiki as I did note see anything referencing this. If there is something somewhere, I must have missed it and it may be worth making it a little clearer. Additionally, there is always the option of potentially listing this as a bug if someone wishes to address this, however I do not know the underbelly of the application and believe my knowledge in this at this time is far too limited to comment on.

Hopefully, this will at least help someone else in future who may encounter this issue.

Thanks

**Comment by 314pies** [comment]
Thanks for sharing markyj2015!
Will add it to wiki later.
