### ISSUE TITLE
[BUG] Useless/Unused Library included

### ISSUE THREAD

**Issue by TheYellowArchitect** [VeriorPies/ParrelSync#28]
![14](https://user-images.githubusercontent.com/25630803/107048027-53d56900-677d-11eb-9277-9d43dad3208b.PNG)

![14](https://user-images.githubusercontent.com/25630803/107048134-710a3780-677d-11eb-8bac-cc3f367111f9.PNG)

I deleted it, and it seems to work - I don't get why there is such a dependency, especially one which is unused

**Enviroment**
* Windows 2018.1.1f1
* ParrelSync 1.4.1

**Comment by kamyker** [comment]
No?

https://github.com/VeriorPies/ParrelSync/blob/master/ParrelSync/Editor/ClonesManager.cs#L1-L14

**Comment by 314pies** [comment]
Yeah, there's some unused namespace being using.
Shouldn't do any harm.
Will clean it up later.
