### ISSUE TITLE
[Question] Do clones have their code updated automatically?

### ISSUE THREAD

**Issue by TheYellowArchitect** [VeriorPies/ParrelSync#30]
I didn't find this in the homepage, so I have to ask:

Do clones have their code updated automatically?
Unity by default auto-refreshes, so, once the code is changed on the original, does it also change on the clones?
Or do I have to build clones for each new build?

**Comment by TheYellowArchitect** [comment]
Ok I did some easy test to confirm this myself

A clone has to recompile (Ctrl+R) or by Unity's auto-refresh

This means a clone doesn't have to be rebuilt each time a code changes (still faster than building manually)
Please put this information onto README.md and I will close this issue, as everyone reading it doesn't fully understand it's really that simple

**Comment by 314pies** [comment]
Yeah,
You can have Auto-Refresh on in Unity, or do it manually by pressing ctrl+r.
I'll put related section in Wiki later.
