### ISSUE TITLE
[Question] ParrelSync namespace undetected - Can't use IsClone()

### ISSUE THREAD

**Issue by TheYellowArchitect** [VeriorPies/ParrelSync#31]
I try to use ClonesManager.IsClone https://github.com/VeriorPies/ParrelSync/wiki/List-of-APIs
Yet, there is nothing detected under ParrelSync, except .UnityNear<T>
I am certain ClonesManager.cs is inside the namespace of ParrelSync

For clarification, inside ClonesManager.cs, IsClone() is a function, so it definitely exists. I guess this is a namespace issue, perhaps related to how the project folder structure is? idk, asking if anyone has a suggestion

**Comment by TheYellowArchitect** [comment]
Turns out the issue is likely that it is inside an Editor folder
Yet, if I pull it out, the rest of ParrelSync breaks (21 errors)

Any suggestion?

**Comment by TheYellowArchitect** [comment]
I found a workaround after hours of thinking, but this is too hacky.
![image](https://user-images.githubusercontent.com/25630803/107156914-ede01180-6935-11eb-8be6-82da37d7cb13.png)

**Comment by j1mmie** [comment]
Huh, running into this as well. Creative workaround there. I suppose something more fault-tolerant would just look for the .clone file

**Comment by 314pies** [comment]
Is this still an issue?

**Comment by happypepper** [comment]
Yes, I am seeing this too
