### ISSUE TITLE
[Question] Sharing Input Between Clones

### ISSUE THREAD

**Issue by TheYellowArchitect** [VeriorPies/ParrelSync#32]
I have only 2 players for my netcoding
This means I have one normal/original project, and one clone_0

For example, I want to move player1, and player2 at the same time. Say, one with WASD, the other with arrow keys (e.g. detected by ClonesManager.IsClone())
I can focus only on one window

I use Windows 7, Unity 2018.1.f1

Is there a way to share input between the windows?
Any way helps!

**Comment by TheYellowArchitect** [comment]
While this is a thing https://www.sevenforums.com/tutorials/9000-mouse-hover-makes-window-active-enable.html
It seems like if I run both Unity windows at the same time, the input is captured for both. No idea if this is a bug or a feature, it just works.

Do put the above on the README.md or the wiki (I can't edit the wiki feelsbadman) and close this issue

**Comment by 314pies** [comment]
Hi,
This is a nice feature I would also like to have.
But this is more related to OS and Unity itself and we probably can't do much here with ParrelSync.
