### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mathias0411** [VeriorPies/ParrelSync#35]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots or video link( Youtube/Vimeo) to help explain the problem.

**Enviroment (please complete the following information):**
 - Unity Editor Version: [e.g. Windows 2019.3.0f6]
 - ParrelSync Version [e.g. 1.2]

**Additional context**

**Comment by mathias0411** [comment]
win32exception

**Comment by 314pies** [comment]
Any more details?
