### ISSUE TITLE
[Question] Parrel Sync doesn't seem to work for Unity Hub 2.4.3

### ISSUE THREAD

**Issue by jeffk1m** [VeriorPies/ParrelSync#36]
I'm not sure if this should be a bug report or a feature request but I tried using ParrelSync with a project that was opened from the latest Unity Hub. When I try to run the clone from the clone manager rather than launching another editor it takes me to Unity Hub and gives me the message "Project is already running". I'm currently using Unity Hub 2.4.3 and Unity Version 2020.3.0f1. Before I upgraded to Unity Hub 2.4.3 I was using Unity Hub 2.2.2 and ParrelSync was working fine.

**Comment by majin1985** [comment]
same issue Unity Hub 2.4.2 + Unity Version 2020.2.1f1

**Comment by Capitano2001** [comment]
I'm using ParellSync 1.4.1, UnityHub 2.4.3 and Unity 2019.4.19f1.
When I want to open  a clone with "Open in New Editor" instead of a new editor with the project clone the hub opens -- what do I do wrong? -- How can I open a clone?

Capitano

**Comment by 314pies** [comment]
Just tested ParrelSync 1.4.2 with UnityHub 2.4.3 with Unity 2020.3.1f1(Windows 10), seems work just fine.
Anymore details?
