### ISSUE TITLE
[BUG] Unity 2021.1.2f1 breaks Parrel Sync

### ISSUE THREAD

**Issue by Amadhia** [VeriorPies/ParrelSync#38]
**Describe the bug**
Creating a clone in Unity 2021.1.2f1 generates this error: "File not found exception: Could not find file"...  Even when trying to clone a freshly created blank project.

The clone creation process then stops and the "Hold on..." floating window just sits there and does nothing.

I'm using Hub 2.4.3, but I was able to successfully create and run a clone in Unity 2020.3.  I was also successfully able to run my 2020.1.17f1 project and clone using Hub 2.4.3

**To Reproduce**
In Unity 2021.1.2f1, (even in a blank, freshly created project), attempt to create a new clone.

**Screenshots/Video**

![80ED9665-F53E-48BD-80EE-51B02D4F6BDA](https://user-images.githubusercontent.com/22459808/114200821-6a797700-990a-11eb-958d-36ff55526562.jpeg)

**Comment by 314pies** [comment]
Hi,
I just tested ParrelSync 1.4.2 with Unity 2021.1.2f1(Windows), it work quite normal.
Which OS are you using?
