### ISSUE TITLE
[BUG] When using Mirror clone freezes.

### ISSUE THREAD

**Issue by 0risin** [VeriorPies/ParrelSync#39]
**When using Mirror clone freezes. As soon as the clone connects online at all, either as server or client**
A clear and concise description of what the bug is. Unity 2020.3.1 LTS

**To Reproduce**
1. Add a Mirror Networking "Network Manager" and "Network HUD" to original Project and enable the HUD
2. Add any GameObject to the Network Managers "Player Prefab" Field.
3.  Go to 'Project Clone'
4. Click on 'Play' in Clone start it as Server in  through Networking HUD
5. In OG Project Click play and connect as Client through Networking HUD
6. See freeze on Clones side.

**Expected behavior**
Doesn't freeze and player spawns.

**Screenshots/Video**
-

**Enviroment (please complete the following information):**
 - Unity Editor Version: [e.g. Windows 2020.3.1f1 LTS]
 - ParrelSync Version [e.g. 1.4.2]

**Additional context**
-

**Comment by 314pies** [comment]
Can you specify the Unity version(ex: Windows 2019.3.0f6) and  ParrelSync(ex: 1.4.2) version to help up reproduce the issue?

**Comment by 314pies** [comment]
Oh,
Are you using Unity Windows 2020.3.1f1 LTS and ParrelSync 1.4.2 ?
