### ISSUE TITLE
[Feature Request] - Support for Linux please!

### ISSUE THREAD

**Issue by Tato-Marinelli** [VeriorPies/ParrelSync#45]
Hello! I've been programming in Unity for the last year using Windows using ParrelSync. I found that this plugin is the most useful tool for a network based game and now that I'm stable using Linux I really miss this feature.

I don't know if I can help with something but it would be great, too!

Thank you.

**Comment by 314pies** [comment]
Hi Tato-Marinelli,
Actually, ParrelSync have add Linux support after version 1.4.2 release :)

**Comment by Tato-Marinelli** [comment]
Sorry, and I even try to find it but I came from the button on the ParrelSync window on Unity. Thank you!
