### ISSUE TITLE
[BUG] PlayerPrefs keep the same values between editor instances

### ISSUE THREAD

**Issue by pawelsalwa** [VeriorPies/ParrelSync#46]
**Describe the bug**
If we change PlayerPrefs value inside any editor (clone or original) all other editors have their changes reflected.

**To Reproduce**
1. Set any PlayerPref value in any editor instance.
2. Read the data on any other editor instance.

**Expected behavior**
Expected - PlayerPrefs value changes are only local to each editor

**Comment by 314pies** [comment]
Hi pawelsalwa ,
PlayerPrefs is an API provided by Unity, and it's probably not a good idea to change it behavior.
Although we can make some kind wrapper to it, as this will effect the final build code and increase project dependency with ParrelSync, it's still more prefer to leave it the developer themselves to decide.

**Comment by 314pies** [comment]
There's a [IsClone](https://github.com/VeriorPies/ParrelSync/wiki/List-of-APIs#clonesmanagerisclone) API to know whether the current editor is clone or not.
You may consider do something like this if you want to have separated PlayerPrefs value for the clone.
```
string key = "playerPrefsKey";

#if UNITY_EDITOR
if (ClonesManager.IsClone()) { key += "_clone";}
#endif

int pValue= PlayerPrefs.GetInt(key , 0);
```
