### ISSUE TITLE
[BUG] package-lock.json is not synchronized

### ISSUE THREAD

**Issue by kyubuns** [VeriorPies/ParrelSync#48]
**Describe the bug**
Updating package-lock.json in the original UnityProject does not sync to the clone.
(I didn't add or remove any packages, I updated the hash.)

**Enviroment (please complete the following information):**
 - Unity Editor Version: macOS 2020.3.6
 - ParrelSync Version: 1.5.0

**Additional context**
There will be a difference `MyProject/Packages/packages-lock.json` and `MyProject_clone_0/Packages/packages-lock.json`

**Comment by 314pies** [comment]
Hi kyubuns,
The "Packages" folder will only be updated when the clone project folder is being opened.
Please re-open the clone project or manual copy the "Package" folder to the clone project folder if you made change related to Packages.

**Comment by kyubuns** [comment]
I have looked into it again, and it seems to not update under certain conditions.
That's when I need to update packages for build pass.

Example:
- Update packages on the main project.
- Write code that uses the newly increased classes in the updated package on the main project.
- Try to open clone project.
- When the source code is copied (by symbolic link), the build of the clone project does not pass, and the code about the copy of Packages does not run.

In my opinion, there's no way around it.

For example,
when I select "Open in New Editor" from the Clone Manager Window of the main project, copy Project before opening. Isn't that a good idea?

**Comment by kyubuns** [comment]
Solved by #48, thanks @314pies
