### ISSUE TITLE
[BUG] Packages are not updated in clone

### ISSUE THREAD

**Issue by sathyarajshetigar** [VeriorPies/ParrelSync#52]
Packages manifest updated in main project does not get replicated in the clone project

**Comment by 314pies** [comment]
Hi, sathyarajshetigar
You might find this helpful. 
https://github.com/VeriorPies/ParrelSync/wiki/Troubleshooting-&-FAQs#why-isnt-my-newly-installed-package-being-synced-to-clone-editors

Also, note there's a packaged-sync issue being fix in the latest 1.5.1 release so you might want to update to that version.

**Comment by sathyarajshetigar** [comment]
Thanks for the fix. please update the UPM as well.
