### ISSUE TITLE
[Solution] Crash when using Firebase

### ISSUE THREAD

**Issue by keyserjaya** [VeriorPies/ParrelSync#53]
Steps to reproduce:
1. Import firebase
2. Play original editor
3. Play 1 clone editor
4. Clone editor crashed

Fix:
For Editor only, use:
`db = FirebaseFirestore.GetInstance(FirebaseApp.Create());`
`db.Settings.PersistenceEnabled = false;`
instead of
`db = FirebaseFirestore.DefaultInstance;`

![image](https://user-images.githubusercontent.com/14213507/130884981-d17caa00-3e05-4ed2-b5d2-5cf27503fd1e.png)

Reference: https://github.com/firebase/quickstart-unity/issues/638

**Comment by somedeveloper00** [comment]
in the Firebase we were using, the syntax was 
```csharp
app = FirebaseApp.Create();
db = FirebaseDatabase.GetInstance(app);
db.SetPersistenceEnabled(true);
```

make sure to __reuse the `app`__ for other FireBase modules like auth and storage. they all have some static `GetInstance(app)` syntax
