### ISSUE TITLE
There is no seperate Playerpref data for seperate instance.

### ISSUE THREAD

**Issue by Sanjay-StreakByte** [VeriorPies/ParrelSync#59]
I am using this plugin, working very fine, i am thankful for this wonderful plugin.

Suggestion :

I am working on multiplayer game using photonnetwok, i am testing with clone manger but there were my playerpref data is right now share with every instance,

is there any way to achieve this functionalities?

Thank you.

**Comment by 314pies** [comment]
Hi Sanjay-StreakByte!

You may find this helpful:
https://github.com/VeriorPies/ParrelSync/wiki/List-of-APIs
