### ISSUE TITLE
Unity HUB

### ISSUE THREAD

**Issue by Hoppyjr4** [VeriorPies/ParrelSync#60]
It appears that ParrelSync doesn't work with the Unity's HUB product.  Is the correct?  If not, how should this be setup?  Hub does prevent a second instance of Unity from running.

**Comment by 314pies** [comment]
Hi Hoppyjr4,
ParrelSync should work perfectly fine with Unity HUB.
Did you encounter any issues?

**Comment by Hoppyjr4** [comment]
Unity HUB 2.5.4 blocks the start of a second Unity Editor running on the same project.  When ParrelSync starts the clone copy Unity Hub comes up and stops the Editor before it can begin.
