### ISSUE TITLE
[BUG] Unity crash on symlink since 2021.2.0b14+ and 2022.1.0a9+

### ISSUE THREAD

**Issue by ghost** [VeriorPies/ParrelSync#61]
**Describe the bug**
ParrelSync doesn't work with Unity 2021.2.0b14+ and 2022.1.0a9+ due to a bug in Unity.

**To Reproduce**
1. Create project with Unity 2021.2.0b14+
2. Clone
3. Open cloned project
4. Crash in `0x00007ff762cbfee1 (Unity) OnDemandScheduler::SetStandbyWorkerCount`

https://issuetracker.unity3d.com/issues/crash-on-ondemandscheduler-setstandbyworkercount-when-opening-a-project-with-a-symbolic-link-in-it
It seems Unity has problem with symbolic links in latest versions.
I am not sure if it's easy to workaround on ParrelSync side (probably not) so please upvote this link so that this gets Unity attention!

**Comment by jmguillemette** [comment]
just tripped on this as well

**Comment by Hadoukanen** [comment]
I manage to get mine working by disabling Directory Monitoring under Asset Pipeline in the prefs. Symlinks does not work with it..
![Capture](https://user-images.githubusercontent.com/883313/139602572-b16d9a92-4c03-4c72-8b63-846c39d77a23.PNG)
.

**Comment by virgile-wp** [comment]
It's now part of "Known Issues in 2021.2.0f1":

> Asset Import Pipeline: There is a crash in OnDemandScheduler::SetStandbyWorkerCount when opening a project with a symbolic link in it. (1370389)

**Comment by brogan89** [comment]
I made some editor methods that just copy the project to a clone. Its not ideal as it takes much longer, but its working fine for now. Its not that bad when just syncing the scripts only and stuff. It will do for the time being anyway. 

```csharp
		[MenuItem("Sync/All", true)]
		[MenuItem("Sync/Scripts", true)]
		[MenuItem("Sync/Prefabs", true)]
		[MenuItem("Sync/Scenes", true)]
		private static bool IsTheClone() => !Directory.GetCurrentDirectory().Contains("_clone");
		[MenuItem("Sync/All")] private static void SyncProject() => SyncPath("Assets", "Packages", "ProjectSettings");
		[MenuItem("Sync/Scripts")] private static void SyncScriptsFolder() => SyncPath("Assets/Scripts");
		[MenuItem("Sync/Prefabs")] private static void SyncPrefabsFolder() => SyncPath("Assets/Prefabs");
		[MenuItem("Sync/Scenes")] private static void SyncScenesFolder() => SyncPath("Assets/Scenes");

		private static void SyncPath(params string[] paths)
		{
			foreach (var path in paths)
			{
				var oldRoot = Directory.GetCurrentDirectory();
				var oldFolder = $"{oldRoot}/{path}";

				var newRoot = $"{oldRoot}_clone";
				var newFolder = $"{newRoot}/{path}";
				
				// create root
				Directory.CreateDirectory(newRoot);
				SyncDir(oldFolder, newFolder);
			}
		}

		private static void SyncDir(string sourcePath, string targetPath)
		{
			if (!Directory.Exists(targetPath))
				Directory.CreateDirectory(targetPath);
			
			// CopyFilesRecursively
			//Now Create all of the directories
			foreach (string dirPath in Directory.GetDirectories(sourcePath, "*", SearchOption.AllDirectories))
				Directory.CreateDirectory(dirPath.Replace(sourcePath, targetPath));

			//Copy all the files & Replaces any files with the same name
			foreach (string newPath in Directory.GetFiles(sourcePath, "*.*",SearchOption.AllDirectories))
				File.Copy(newPath, newPath.Replace(sourcePath, targetPath), true);
			
			Debug.Log($"Synced: <b>{sourcePath}</b> to <b>{targetPath}</b>");
		}
```

**Comment by brogan89** [comment]
> I manage to get mine working by disabling Directory Monitoring under Asset Pipeline in the prefs. Symlinks does not work with it.. ![Capture](https://user-images.githubusercontent.com/883313/139602572-b16d9a92-4c03-4c72-8b63-846c39d77a23.PNG) .

This also works too. Thanks for the tip :)

**Comment by virgile-wp** [comment]
![image](https://user-images.githubusercontent.com/93170922/141744210-27e240f8-507d-4ff5-ad26-bc419749cf38.png)
Source: https://issuetracker.unity3d.com/issues/crash-on-ondemandscheduler-setstandbyworkercount-when-opening-a-project-with-a-symbolic-link-in-it
