### ISSUE TITLE
[BUG] Scriptable objects' values are not updated/synchronized automatically.

### ISSUE THREAD

**Issue by KCrossX** [VeriorPies/ParrelSync#69]
**Describe the bug**
Scriptable objects' values are not updated/synchronized. (Scriptable object creation are synced)

**To Reproduce**
1. Create any scriptable object on the main project
2. Change window focus to cloned project (parrelsync will refresh directory as expected.
3. Go back to main project, then change any value/s in the scriptable objects
4. Go to the cloned project and inspect the scriptable object

**Expected behavior**
The scriptable object should contain updated values, but right now it does not.

**Screenshots/Video**
none

**Enviroment (please complete the following information):**
 - Unity Editor Version: (For Example: Windows 2020.3.11f1)
 - ParrelSync Version: 1.5.0
 - OS Version: Windows 10

**Additional context**
Current alternatives are either:
- manually updating the value/s in the cloned project
- change scriptable object name in the main project then switch to the cloned project
- reopening both main and cloned projects to force value updates.
which are a hassle to do when doing mass updating scriptable objects.

**Comment by 0x-1** [comment]
Does File -> Save Project solve this problem?

I remember uEcho had the same Problem as Unity does not immediatly serialize stuff to the disk but keeps it in-library/cached state.

**Comment by KCrossX** [comment]
Oh my, it seems to work.

I'll start using this (underused) Save Project more often. Sure it's not automatic, but it's literally just one button to synchronize (hopefully all stuff).

Thank you @0x-1 for your help.

**Comment by tgienger** [comment]
Saving does not update the values for me at all.
