### ISSUE TITLE
[BUG]  Unable to open clone projects from Clones Manager

### ISSUE THREAD

**Issue by Zapgun** [VeriorPies/ParrelSync#8]
**Describe the bug**
I am using the HDRP pipeline with a simple scene.

After cloning the project, clicking the 'Open in New Editor' fails, and running the cloned project directly generates this error:

![unknown](https://user-images.githubusercontent.com/330793/94046753-04436180-fdc9-11ea-8de2-af12bf42fd3b.png)

Copying this missing directory (LocalPackages) to the clone allows the cloned project to be opened directly, but it still fails to open when trying the 'Open in New Editor' option in ParrelSync.

**Comment by 314pies** [comment]
I just created a HDRP project with Unity 2019.3.12f1(Windows) and test it with ParallelSync 1.4. 
It works quite normal.

What Unity and ParrelSync version are you using?
Would you mind to share the project files?

**Comment by Zapgun** [comment]
Latest version of ParrelSync (1.3.3) and version 2020.1.6f1 of Unity. Afraid I've since loaded some custom assets into the project so won't be able to share unfortunately. :(

**Comment by 314pies** [comment]
Just test with Unity 2019.3.12f1(Windows) and ParallelSync 1.3.3 and still unable to reproduce this issue.
Any clear instruction to reproduce it?

**Comment by Zapgun** [comment]
Here's the project stripped down (and still not working).

 Hopefully that will help. 

https://drive.google.com/file/d/1u8lJtQg6eXecPTPPKhbN6RSCM8gFny8E/view?usp=sharing

**Comment by 314pies** [comment]
OK, will take a deeper look later.

**Comment by 314pies** [comment]
I've successfully reproduced the result with the project you shared.

This new release should able to clone the project with localPackages folder and open it from clones manager window correctly.
https://github.com/VeriorPies/ParrelSync/releases/tag/1.4.1

**Comment by Zapgun** [comment]
Cheers and thanks 314pies.. glad you figured it out! :)

**Comment by Zapgun** [comment]
Confirmed to be working at my end as well!
