### ISSUE TITLE
[BUG] ScriptableObject do not sync when being edited by custom editor

### ISSUE THREAD

**Issue by Bl4ck-orig** [VeriorPies/ParrelSync#82]
**Describe the bug**
When an asset created by a class deriving from ScriptableObject is changed by a custom editor, the changes are not synced.

**To Reproduce**
1. Create new Unity Project 2020.3.36f1.
2. Create File "ParalSyncEditorBug.cs" and copy code into file at the bottom.
3. Create asset by right clicking in Project Window -> create/ParalSyncEditorBug.
4. Create entry in the created asset for "Test Variable".
5. Clone Project.
6. Click Clear Data Button.
7. Save File & Project.

**Expected behavior**
The asset is synced in both projects.

**Screenshots/Video**
![ParelSyncEditorBug](https://user-images.githubusercontent.com/38137603/175793970-714eeaee-27a7-4990-8fa6-e102e63e69f0.png)

**Enviroment (please complete the following information):**
 - Unity Editor Version:  2020.3.36f1
 - ParrelSync Version: 1.5.1
 - OS Version: Windows 10 21H2

**Additional context**
ParalSyncEditorBug.cs:
```
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[CreateAssetMenu(fileName = "ParalSyncEditorBug", menuName = "ParalSyncEditorBug")]
public class ParalSyncEditorBug : ScriptableObject
{
    [SerializeField] private List<int> testVariable;

    public void ClearData() => testVariable = null;
}

[CustomEditor(typeof(ParalSyncEditorBug))]
public class ParalSyncEditorBugEditor : Editor
{
    public override void OnInspectorGUI()
    {
        ParalSyncEditorBug test = (ParalSyncEditorBug)target;

        DrawDefaultInspector();

        if (GUILayout.Button("Clear Data"))
            test.ClearData();
    }
}
```

**Comment by 314pies** [comment]
Hi Bl4ck-orig,

It seems you didn't mark the scriptable object as dirty after you cleared the data.
Can you try to add ```EditorUtility.SetDirty(test);``` after the line ```test.ClearData();```?

The final result should be somehow like this:
```
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[CreateAssetMenu(fileName = "ParalSyncEditorBug", menuName = "ParalSyncEditorBug")]
public class ParalSyncEditorBug : ScriptableObject
{
    [SerializeField] private List<int> testVariable;

    public void ClearData() => testVariable = null;
}

[CustomEditor(typeof(ParalSyncEditorBug))]
public class ParalSyncEditorBugEditor : Editor
{
    public override void OnInspectorGUI()
    {
        ParalSyncEditorBug test = (ParalSyncEditorBug)target;

        DrawDefaultInspector();

        if (GUILayout.Button("Clear Data")) {
            test.ClearData();
            EditorUtility.SetDirty(test);
        }
    }
}
```

**Comment by Bl4ck-orig** [comment]
Hello.

Did not know about this function! My bad. 

Thank you!

Cheers.
