### ISSUE TITLE
[BUG] When I clone my project it gets cloned but does not clone my assets and project settings

### ISSUE THREAD

**Issue by Mid-D-Man** [VeriorPies/ParrelSync#95]
**Describe the bug**
When I clone my project it gets cloned but does not Cole with my assets and project settings so when I try to open the cloned project it says the file is not supported and doesn't show up in the unity hub it gives me this two errors when I clone
1) /bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `ln -s /Users/mac/Desktop/StickToTheDeath/Stick\ to\ the\ death\ (urp)\ m.copy.2/Assets /Users/mac/Desktop/StickToTheDeath/Stick\ to\ the\ death\ (urp)\ m.copy.2_clone_1/Assets'

UnityEngine.Debug:LogError (object)
ParrelSync.ClonesManager:ExecuteBashCommand (string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:657)
ParrelSync.ClonesManager:CreateLinkMac (string,string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:324)
ParrelSync.ClonesManager:LinkFolders (string,string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:378)
ParrelSync.ClonesManager:CreateCloneFromPath (string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:113)
ParrelSync.ClonesManager:CreateCloneFromCurrent () (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:64)
ParrelSync.ClonesManagerWindow:OnGUI () (at Assets/ParrelSync/ParrelSync/Editor/ClonesManagerWindow.cs:180)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

2) /bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `ln -s /Users/mac/Desktop/StickToTheDeath/Stick\ to\ the\ death\ (urp)\ m.copy.2/ProjectSettings /Users/mac/Desktop/StickToTheDeath/Stick\ to\ the\ death\ (urp)\ m.copy.2_clone_1/ProjectSettings'

UnityEngine.Debug:LogError (object)
ParrelSync.ClonesManager:ExecuteBashCommand (string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:657)
ParrelSync.ClonesManager:CreateLinkMac (string,string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:324)
ParrelSync.ClonesManager:LinkFolders (string,string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:378)
ParrelSync.ClonesManager:CreateCloneFromPath (string) (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:114)
ParrelSync.ClonesManager:CreateCloneFromCurrent () (at Assets/ParrelSync/ParrelSync/Editor/ClonesManager.cs:64)
ParrelSync.ClonesManagerWindow:OnGUI () (at Assets/ParrelSync/ParrelSync/Editor/ClonesManagerWindow.cs:180)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

**To Reproduce**

it just happens when ever I try to clone my main project but not any new project I create so I don't know weather its from the files or something

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots or video link( Youtube/Vimeo) to help explain the problem.

**Enviroment (please complete the following information):**
 - Unity Editor Version: (For Example: Windows 2019.3.0f6)
 - ParrelSync Version: (For Example: 1.4.3)
 - OS Version: (For Example:Windows 10 21H1, macOS Big Sur, Ubuntu 20.04 LTS)
I'm using unity version 2022.1.23f1
**Additional context**

**Comment by mccorkle** [comment]
I'm going to take a WILD guess and say that you are seeing this because your project's name has spaces and parenthesis in it.  Rename your project to remove the parenthesis, and I bet it will work like a champ.  

If this fixes it, the developer would just need to escape (or quote) the project folder names in his `ln -s` statement for Linux and MacOS.

**Comment by Gabzee** [comment]
Oh dare god it was that simple goddammit no I feel stupid anyway thanks It
fixed the issuse

**Comment by JK0089** [comment]
I had the same issue, space in project name were the problem.  Would be great if this was a little better signposted!

**Comment by 314pies** [comment]
(wiki page updated: https://github.com/VeriorPies/ParrelSync/issues/95)
