### ISSUE TITLE
[BUG] Creating clone doesn't copy everything and the cloned project cannot be opened.

### ISSUE THREAD

**Issue by gbradburn** [VeriorPies/ParrelSync#96]
I am trying to create a clone of a multiplayer project for testing. I get no errors when creating the clone but the clone is missing most of the folders from the original project and Unity Hub won't let me add it because it says it's not a valid project.

**To Reproduce**
1. ParrelSync Clones Manager
2. Add new clone
3. Wait for it to finish creating the clone
4. Click Open in New Editor
5. Unity Hub opens but the clone doesn't appear. Trying to add it gives the error that it can't be added because it's not a valid project.

**Expected behavior**
A valid clone of the project should be created.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/5175789/214374558-5b470771-871d-4da2-ba4b-3b11bef7be60.png)

**Enviroment (please complete the following information):**
 - Unity Editor Version: Windows 2021.3.16f1
 - ParrelSync Version: 1.5.1
 - OS Version: Windows 10

**Additional context**
Add any other context about the problem here
[ParrelSync log.txt](https://github.com/VeriorPies/ParrelSync/files/10492841/ParrelSync.log.txt)
e.

**Comment by MrPatben8** [comment]
I did some digging. Does your project happen to be on a external drive or a non NTFS drive? It seems only NTFS drives are required to support the symbolic links that are used for the clones.

**Comment by gbradburn** [comment]
Thanks for digging. No, my project is on an internal SSD.

**Comment by MrPatben8** [comment]
Is the SSD your C drive? And is it formatted as NTFS? I fixed my issues by moving the project to my C drive. In any case the issue certainly seems to be because windows can't creat a symbolic link to your project. Hope you can get it sorted

**Comment by gbradburn** [comment]
Hmm, the project drive (F) in my case is actually exFAT, not NTFS.

**Comment by gbradburn** [comment]
I think my D drive is NTFS but it's not an SSD :(
I'll give that a try. I guess I can close this "bug" since we now know what the issue is.
