### ISSUE TITLE
Clicking on Open In New Editor just opens Unity Hub

### ISSUE THREAD

**Issue by NonzeroCornet** [VeriorPies/ParrelSync#97]
I downloaded the latest ParrelSync, 1.5.1, and installed to my project. I have Unity 2021.3.16f Personal running on the project, and I have Unity Hub 3.4.1. 
![image](https://user-images.githubusercontent.com/28660045/215286452-d61bab02-a156-4cfd-accf-0ce857d2d993.png)
When I click the button, it just opens Unity Hub.

**Comment by DancingAppsDays** [comment]
Yes, this happens to me to on 2021.3.11 on Unity Hub 3.2

**Comment by MrPatben8** [comment]
I'm having the exact same issue on 2021.3.18f.
The clone folder is basically empty.

**Comment by MrPatben8** [comment]
Yeah, that's the issue. I moved my project to my C drive and it worked just fine. Hope you can get it sorted, good luck.

**Comment by arkms** [comment]
Is required the drive use NTFS format. (C is always NTFS).

**Comment by 314pies** [comment]
Please see:   
https://github.com/VeriorPies/ParrelSync/wiki/Troubleshooting-&-FAQs#cant-clone-the-project--cant-open-the-cloned-project
(Closing issue)
